# Generated by Django 5.2.3 on 2025-06-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
